displayName=Clan Applicants Webhook
author=PorcupineFish
description=A tiny plugin to capture clan applicants game message
tags=clan,apply,webhook
plugins=com.clan.applicants.webhook.ClanApplicantsWebhook
build=standard